### ISSUE TITLE
Fix bem preset

### ISSUE THREAD

**Issue by sipayRT** [bem/jscs-bem#4]
Tests are failed with `jscs` 1.12.0

**Comment by qfox** [comment]
I need to look at them. Will do it soon.

**Comment by qfox** [comment]
Proposal fix: #5

**Comment by qfox** [comment]
#5 was merged. Is it fine now?

**Comment by qfox** [comment]
ping @sipayRT

**Comment by sipayRT** [comment]
sorry :)
